kind: pipeline
type: docker
name: pull_dir_on_merge

clone:
  disable: true

steps:
- when:
    branch:
    - master
    event:
    - push
  name: ssh_pull_on_work_dir
  image: appleboy/drone-ssh
  environment:
      PLUGIN_ENVS: ssh_key_url, container_name, volume_url
      SSH_KEY_URL:
        from_secret: ssh_key_url
      CONTAINER_NAME:
        from_secret: container_name
      VOLUME_URL:
        from_secret: volume_url
  volumes:
  - name: api-faketransfer
    path: /home/.VOLUMES/SITE__Cpacash.pro/
  settings:
    username: gitea-volumes
    key:
      from_secret: site_key_ssh
    host:
      from_secret: site_host_ssh
    script:
#      - eval "$(ssh-agent -s)"
       - echo Linux
#      - ssh-add $SSH_KEY_URL 4
#      - cd $VOLUME_URL
#      - git reset --hard
#      - git pull origin master
#      - docker restart $CONTAINER_NAME
